// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFGFD1wJQps9csewhlLeIQENT02s4kEQ',
    appId: '1:936392936508:web:c29b47cd311ba10be08739',
    messagingSenderId: '936392936508',
    projectId: 'farmersupportchatbot',
    authDomain: 'farmersupportchatbot.firebaseapp.com',
    storageBucket: 'farmersupportchatbot.firebasestorage.app',
    measurementId: 'G-99C8YGDRQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_021qXEyZezDorijhzIbBs48ZFBdx3w',
    appId: '1:936392936508:android:b33af838537be48fe08739',
    messagingSenderId: '936392936508',
    projectId: 'farmersupportchatbot',
    storageBucket: 'farmersupportchatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu4Kw1pusB37U4I6SIujTjcud-TmNhQ2E',
    appId: '1:936392936508:ios:5515aca4077beacfe08739',
    messagingSenderId: '936392936508',
    projectId: 'farmersupportchatbot',
    storageBucket: 'farmersupportchatbot.firebasestorage.app',
    iosBundleId: 'com.example.farmerChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu4Kw1pusB37U4I6SIujTjcud-TmNhQ2E',
    appId: '1:936392936508:ios:5515aca4077beacfe08739',
    messagingSenderId: '936392936508',
    projectId: 'farmersupportchatbot',
    storageBucket: 'farmersupportchatbot.firebasestorage.app',
    iosBundleId: 'com.example.farmerChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgFGFD1wJQps9csewhlLeIQENT02s4kEQ',
    appId: '1:936392936508:web:687ad6a976143cd8e08739',
    messagingSenderId: '936392936508',
    projectId: 'farmersupportchatbot',
    authDomain: 'farmersupportchatbot.firebaseapp.com',
    storageBucket: 'farmersupportchatbot.firebasestorage.app',
    measurementId: 'G-R3ESC3GMTR',
  );
}
